### ISSUE TITLE
within = NULL

### ISSUE THREAD

**Issue by Ribeiro-J** [saulo-chaves/ProbBreed#3]
Bom dia, tudo bem? Parabéns pelo pacote.

O R tem me retornado alguns erros que não entendi o problema:
**> head(results$within$perfo$gl)
NULL
> plot(results, category = "perfo", level = "within")
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' deve ser atômico
> plot(results, category = "stabi")
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' deve ser atômico
> plot(results, category = "pair_stabi")
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' deve ser atômico
> plot(results, category = "joint")
Error in `.data$level`:
! Column `level` not found in `.data`.
Run `rlang::last_trace()` to see where the error occurred.**

Saberia me orientar o problema que estou tendo? Desde já agradeço pela atenção.

**Comment by saulo-chaves** [comment]
Bom dia! Obrigado por utilizar o pacote!! 

Você poderia dar mais detalhes? Por exemplo, qual a versão do pacote? Qual o código utilizado para as funções bayes_met, extr_outs e prob_sup? Pergunto pois, por exemplo, na última versão, modelos que entram com médias ajustadas não estimam a variância da interação genótipos x ambientes (gl), uma vez que ela é confundida com o resíduo. Logo, probabilidades que necessitam dela não podem ser estimadas. 
Espero sua reposta para poder te ajudar melhor

At.te

Saulo

**Comment by saulo-chaves** [comment]
Vou dar esse issue como resolvido. Caso tenha problemas, por favor, reabra. Obrigado.
